// <auto-generated />
using LojaVirtual.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LojaVirtual.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180221144754_migracaoInicial")]
    partial class migracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LojaVirtual.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1200);

                    b.Property<string>("Imagem")
                        .HasMaxLength(200);

                    b.Property<string>("ImagemThumbnail")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<int?>("SubCategoriaId");

                    b.Property<bool>("Visivel");

                    b.HasKey("CategoriaId");

                    b.HasIndex("SubCategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("LojaVirtual.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<int?>("CategoriaId");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1200);

                    b.Property<string>("Imagem")
                        .HasMaxLength(200);

                    b.Property<string>("ImagemThumbnail")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<bool>("Visivel");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("LojaVirtual.Models.SubCategoria", b =>
                {
                    b.Property<int>("SubCategoriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1200);

                    b.Property<string>("Imagem")
                        .HasMaxLength(200);

                    b.Property<string>("ImagemThumbnail")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<bool>("Visivel");

                    b.HasKey("SubCategoriaId");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("LojaVirtual.Models.Categoria", b =>
                {
                    b.HasOne("LojaVirtual.Models.SubCategoria")
                        .WithMany("Categoria")
                        .HasForeignKey("SubCategoriaId");
                });

            modelBuilder.Entity("LojaVirtual.Models.Departamento", b =>
                {
                    b.HasOne("LojaVirtual.Models.Categoria")
                        .WithMany("Departamento")
                        .HasForeignKey("CategoriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
